[workspace]
authors = ["Ashwin V. Mohanan <ashwin.mohanan@enccs.se>"]
channels = ["conda-forge"]
name = "5-intro-to-gpu-prog-models-high-level"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.9,<3.14"
cupy = ">=13.6.0,<14"
jupyterlab = ">=4.1.0,<5"
ipython = ">=9.7.0,<10"
numba-cuda = ">=0.20.1,<0.21"

[pypi-dependencies]
jupyterlab-rise = ">=0.43.1, <0.44"
